In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv(r"C:\Users\abhay.bhandari\Jupyter files\Practice files\New folder\endangeredLang.csv")

In [3]:
data.head()

,ID,Name in English,Name in French,Name in Spanish,Countries,Country codes alpha 3,ISO639-3 codes,Degree of endangerment,Alternate names,Name in the language,Number of speakers,Sources,Latitude,Longitude,Description of the location
0,1022,South Italian,italien du sud,napolitano-calabrés,Italy,ITA,nap,Vulnerable,Neapolitan; Neapolitan-Calabrese; неаполитанск...,NaN,7500000.0,NaN,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,sicilien,siciliano,Italy,ITA,scn,Vulnerable,NaN,NaN,5000000.0,NaN,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,bas-saxon,bajo sajón,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS","act, drt, frs, gos, nds, sdz, stl, twd, vel, wep",Vulnerable,"Low German, Niedersächsisch, Nedersaksisch, Ni...",Neddersassisch,4800000.0,NaN,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,biélorusse,bielorruso,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",bel,Vulnerable,NaN,NaN,4000000.0,Hienadź Cychun: Weißrussisch. — Lexikon der Sp...,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,lombard,lombardo,"Italy, Switzerland","ITA, CHE",lmo,Definitely endangered,NaN,NaN,3500000.0,NaN,45.7215,9.3273,the region of Lombardy (except the southernmos...

In [8]:
data.describe()

                ID  Number of speakers     Latitude    Longitude
count  2722.000000        2.539000e+03  2719.000000  2719.000000
mean   1362.501102        5.365890e+04    16.247853    22.266012
std     785.919949        3.114620e+05    23.241828    92.611293
min       2.000000        0.000000e+00   -55.002800  -174.197800
25%     682.250000        5.000000e+01    -2.705000   -69.180850
50%    1362.500000        8.000000e+02    15.658700    30.591400
75%    2042.750000        6.872000e+03    34.214050   102.366000
max    2724.000000        7.500000e+06    77.481500   179.187000

In [16]:
data.sort_values(by = "Number of speakers", ascending = False).head()

,ID,Name in English,Name in French,Name in Spanish,Countries,Country codes alpha 3,ISO639-3 codes,Degree of endangerment,Alternate names,Name in the language,Number of speakers,Sources,Latitude,Longitude,Description of the location
0,1022,South Italian,italien du sud,napolitano-calabrés,Italy,ITA,nap,Vulnerable,Neapolitan; Neapolitan-Calabrese; неаполитанск...,NaN,7500000.0,NaN,40.9798,15.2490,"Campania, Lucania (Basilicata), Abruzzi (Abruz..."
1,1023,Sicilian,sicilien,siciliano,Italy,ITA,scn,Vulnerable,NaN,NaN,5000000.0,NaN,37.4399,14.5019,"Sicily (Sicilia), southern and central Calabri..."
2,383,Low Saxon,bas-saxon,bajo sajón,"Germany, Denmark, Netherlands, Poland, Russian...","DEU, DNK, NLD, POL, RUS","act, drt, frs, gos, nds, sdz, stl, twd, vel, wep",Vulnerable,"Low German, Niedersächsisch, Nedersaksisch, Ni...",Neddersassisch,4800000.0,NaN,53.4029,10.3601,"northern Germany, the north-eastern part of th..."
3,335,Belarusian,biélorusse,bielorruso,"Belarus, Latvia, Lithuania, Poland, Russian Fe...","BRB, LVA, LTU, POL, RUS, UKR",bel,Vulnerable,NaN,NaN,4000000.0,Hienadź Cychun: Weißrussisch. — Lexikon der Sp...,53.9560,27.5756,Belarus except the Polesian-speaking south-wes...
4,382,Lombard,lombard,lombardo,"Italy, Switzerland","ITA, CHE",lmo,Definitely endangered,NaN,NaN,3500000.0,NaN,45.7215,9.3273,the region of Lombardy (except the southernmos...

In [41]:
data.groupby(['Countries','Degree of endangerment']).count()

# val.sort_values(by = 'Number of speakers').head()

                                                                           ID  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered    2
                                                   Definitely endangered    5
                                                   Severely endangered      4
                                                   Vulnerable               1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered      1
...                                                                        ..
Viet Nam                                           Severely endangered      2
                                                   Vulnerable               4
Western Sahara                                     Critically endangered    1
Yemen                                              Definitely endangered    1
                                                   Severely endangered      1

                                                                           Name in English  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                 2
                                                   Definitely endangered                 5
                                                   Severely endangered                   4
                                                   Vulnerable                            1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                   1
...                                                                                    ...
Viet Nam                                           Severely endangered                   2
                                                   Vulnerable                            4
Western Sahara                                     Critically endangered                 1
Yemen                                              Definitely endangered                 1
                                                   Severely endangered                   1

                                                                           Name in French  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                2
                                                   Definitely endangered                5
                                                   Severely endangered                  4
                                                   Vulnerable                           1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                  1
...                                                                                   ...
Viet Nam                                           Severely endangered                  2
                                                   Vulnerable                           4
Western Sahara                                     Critically endangered                1
Yemen                                              Definitely endangered                1
                                                   Severely endangered                  1

                                                                           Name in Spanish  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                 2
                                                   Definitely endangered                 5
                                                   Severely endangered                   4
                                                   Vulnerable                            1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                   1
...                                                                                    ...
Viet Nam                                           Severely endangered                   2
                                                   Vulnerable                            4
Western Sahara                                     Critically endangered                 1
Yemen                                              Definitely endangered                 1
                                                   Severely endangered                   1

                                                                           Country codes alpha 3  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                       2
                                                   Definitely endangered                       5
                                                   Severely endangered                         4
                                                   Vulnerable                                  1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                         1
...                                                                                          ...
Viet Nam                                           Severely endangered                         2
                                                   Vulnerable                                  4
Western Sahara                                     Critically endangered                       1
Yemen                                              Definitely endangered                       1
                                                   Severely endangered                         1

                                                                           ISO639-3 codes  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                2
                                                   Definitely endangered                5
                                                   Severely endangered                  4
                                                   Vulnerable                           1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                  1
...                                                                                   ...
Viet Nam                                           Severely endangered                  2
                                                   Vulnerable                           3
Western Sahara                                     Critically endangered                1
Yemen                                              Definitely endangered                0
                                                   Severely endangered                  1

                                                                           Alternate names  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                 2
                                                   Definitely endangered                 3
                                                   Severely endangered                   4
                                                   Vulnerable                            0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                   1
...                                                                                    ...
Viet Nam                                           Severely endangered                   1
                                                   Vulnerable                            2
Western Sahara                                     Critically endangered                 1
Yemen                                              Definitely endangered                 1
                                                   Severely endangered                   1

                                                                           Name in the language  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                      0
                                                   Definitely endangered                      0
                                                   Severely endangered                        0
                                                   Vulnerable                                 0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                        0
...                                                                                         ...
Viet Nam                                           Severely endangered                        0
                                                   Vulnerable                                 0
Western Sahara                                     Critically endangered                      0
Yemen                                              Definitely endangered                      0
                                                   Severely endangered                        0

                                                                           Number of speakers  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                    2
                                                   Definitely endangered                    5
                                                   Severely endangered                      4
                                                   Vulnerable                               0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                      0
...                                                                                       ...
Viet Nam                                           Severely endangered                      2
                                                   Vulnerable                               4
Western Sahara                                     Critically endangered                    1
Yemen                                              Definitely endangered                    1
                                                   Severely endangered                      1

                                                                           Sources  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered         2
                                                   Definitely endangered         5
                                                   Severely endangered           4
                                                   Vulnerable                    0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered           1
...                                                                            ...
Viet Nam                                           Severely endangered           0
                                                   Vulnerable                    3
Western Sahara                                     Critically endangered         1
Yemen                                              Definitely endangered         1
                                                   Severely endangered           1

                                                                           Latitude  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered          2
                                                   Definitely endangered          5
                                                   Severely endangered            4
                                                   Vulnerable                     1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered            1
...                                                                             ...
Viet Nam                                           Severely endangered            2
                                                   Vulnerable                     4
Western Sahara                                     Critically endangered          1
Yemen                                              Definitely endangered          1
                                                   Severely endangered            1

                                                                           Longitude  \
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered           2
                                                   Definitely endangered           5
                                                   Severely endangered             4
                                                   Vulnerable                      1
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered             1
...                                                                              ...
Viet Nam                                           Severely endangered             2
                                                   Vulnerable                      4
Western Sahara                                     Critically endangered           1
Yemen                                              Definitely endangered           1
                                                   Severely endangered             1

                                                                           Description of the location
Countries                                          Degree of endangerment
Afghanistan                                        Critically endangered                             2
                                                   Definitely endangered                             5
                                                   Severely endangered                               4
                                                   Vulnerable                                        0
Albania, Algeria, Bosnia and Herzegovina, Bulga... Severely endangered                               1
...                                                                                                ...
Viet Nam                                           Severely endangered                               0
                                                   Vulnerable                                        0
Western Sahara                                     Critically endangered                             1
Yemen                                              Definitely endangered                             1
                                                   Severely endangered                               1

[531 rows x 13 columns]

In [70]:
from pandas.core.groupby import DataFrameGroupBy

India_Lang = data[data["Countries"] == "India"]
India_Lang = India_Lang.groupby[["Name in English", "Number of speakers"]]
# India_df = India_Lang.to
# # India_df.to_csv("IndiaLang.csv")

,ID,Name in English,Name in French,Name in Spanish,Countries,Country codes alpha 3,ISO639-3 codes,Degree of endangerment,Alternate names,Name in the language,Number of speakers,Sources,Latitude,Longitude,Description of the location
7,1586,Gondi,gondi,gondí,India,IND,gon,Vulnerable,Gondi; Gaudi; Gondiva; Gondwadi; Goondile; Gou...,NaN,2713790.0,NaN,19.5804,80.4418,"Madhya Pradesh (Betul, Chhindwara, Seoni, Mand..."
16,1591,Kurux (India),kurux (Inde),kuruj (India),India,IND,kru,Vulnerable,Kurukh; Oraon,NaN,1751489.0,NaN,22.1467,85.2758,Jharkhand and Bihar
18,1585,Tulu,tulu,tulú,India,IND,tcy,Vulnerable,Tuluva Bhasa; Tullu; Thulu; Tal; Tilu; Thalu\n,NaN,1722768.0,NaN,12.0178,75.7067,"Karnataka, Andhra Pradesh, Kerala"
19,1556,Kangdi,Kangdi,kangdi,India,IND,xnr,Definitely endangered,Dogaryali; Dogri Pahari; Tokkaru; Dogri-Kangr...,NaN,1700000.0,NaN,32.4356,76.1242,Himachal Pradesh
26,1227,Meithei,meitei,mitei,India,IND,mni,Vulnerable,"Manipuri, Meitei",NaN,1250000.0,NaN,24.7667,93.8946,"Manipur (throughout, but concentrated in the M..."